name: document-lists

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      Server_AT:
        required: true
      AccountName_AT:
        required: true
      AppPassword_AT:
        required: true
      Path_AllListsMetadataJson:
        required: true

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8'

      - name: Restore packages
        run: dotnet restore --locked-mode

      - name: Install realpath tool
        run: sudo apt-get install -y realpath

      - name: Document lists
        env:
          Server_AT: ${{ secrets.Server_AT }}
          AccountName_AT: ${{ secrets.AccountName_AT }}
          AppPassword_AT: ${{ secrets.AppPassword_AT }}
          Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}
        run: |
          mkdir -p output-docs
          dotnet run --project ./ListSky.App/ListSky.App.csproj document $(realpath output-docs)

      # - name: Push new documents to branch
      #   uses: actions4git/add-commit-push@v1