name: on-push-to-main-apply

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  on-push-to-main-apply:
    uses: ./.github/workflows/actions/push-to-bluesky.yaml
    secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        Server_AT: ${{ secrets.Server_AT }}
        AccountName_AT: ${{ secrets.AccountName_AT }}
        AppPassword_AT: ${{ secrets.AppPassword_AT }}
        Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}
