name: on-push-to-main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
    secrets:
      Server_AT: ${{ secrets.Server_AT }}
      AccountName_AT: ${{ secrets.AccountName_AT }}
      AppPassword_AT: ${{ secrets.AppPassword_AT }}
      Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}

  apply-lists:
    needs: run-tests
    uses: ./.github/workflows/push-to-bluesky.yaml
    secrets:
        Server_AT: ${{ secrets.Server_AT }}
        AccountName_AT: ${{ secrets.AccountName_AT }}
        AppPassword_AT: ${{ secrets.AppPassword_AT }}
        Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}
