name: on-push-to-main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
    secrets:
      Server_AT: ${{ secrets.Server_AT }}
      AccountName_AT: ${{ secrets.AccountName_AT }}
      AppPassword_AT: ${{ secrets.AppPassword_AT }}
      Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}

  apply:
    needs: run-tests
    uses: ./.github/workflows/push-to-bluesky.yaml
    secrets:
        Server_AT: ${{ secrets.Server_AT }}
        AccountName_AT: ${{ secrets.AccountName_AT }}
        AppPassword_AT: ${{ secrets.AppPassword_AT }}
        Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}

  document-lists:
    needs: apply
    uses: ./.github/workflows/document-lists.yaml
    secrets:
        Server_AT: ${{ secrets.Server_AT }}
        AccountName_AT: ${{ secrets.AccountName_AT }}
        AppPassword_AT: ${{ secrets.AppPassword_AT }}
        Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}
  