name: on-pull-request

on:
  workflow_dispatch:
  pull_request:
    # paths:
    #   - "Data/*.csv"
    #   - "Data/*.json"

permissions:
  contents: write
  pull-requests: write

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
    secrets:
        Server_AT: ${{ secrets.Server_AT }}
        AccountName_AT: ${{ secrets.AccountName_AT }}
        AppPassword_AT: ${{ secrets.AppPassword_AT }}
        Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}
