name: run-tests

on:
  workflow_call:
    secrets:
      Server_AT:
        required: true
      AccountName_AT:
        required: true
      AppPassword_AT:
        required: true
      Path_AllListsMetadataJson:
        required: true

jobs:
  run-all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8'

      - name: Restore packages
        run: dotnet restore --locked-mode

      - name: Build solution
        run: dotnet build

      - name: Run tests
        working-directory: ./ListSky.Tests
        env:
            Server_AT: ${{ secrets.Server_AT }}
            AccountName_AT: ${{ secrets.AccountName_AT }}
            AppPassword_AT: ${{ secrets.AppPassword_AT }}
            Path_AllListsMetadataJson: ${{ secrets.Path_AllListsMetadataJson }}
            GITHUB_REPO: ${{ github.repository }}
            GITHUB_USER: ${{ github.repository_owner }}
        run: |
          dotnet test --verbosity:normal
